"""empty message

Revision ID: c820d7865b14
Revises: eb785f3f5d99
Create Date: 2025-03-05 00:50:35.112633

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "c820d7865b14"
down_revision: Union[str, None] = "eb785f3f5d99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matches",
        "current_game_state",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=26),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matches",
        "current_game_state",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=26),
        nullable=True,
    )
    # ### end Alembic commands ###
