"""empty message

Revision ID: eb785f3f5d99
Revises: a268ed9a46ea
Create Date: 2025-03-04 21:46:40.881401

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "eb785f3f5d99"
down_revision: Union[str, None] = "a268ed9a46ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matches",
        "score",
        existing_type=mysql.VARCHAR(
            collation="utf8mb4_unicode_ci", length=1000
        ),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matches",
        "score",
        existing_type=sa.JSON(),
        type_=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=1000),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
